package desi.rnp.jdbc.proxy.handler;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import desi.rnp.jdbc.proxy.JdbcProxyFactory;


public class ProxyConnectionHandler extends ProxyObjectInvocationHandlerSupport<Connection> {

	public ProxyConnectionHandler(JdbcProxyFactory proxyFactory, Connection nativeObject) {
		super(proxyFactory, nativeObject);
	}

	public DatabaseMetaData getMetaData() throws SQLException {
		DatabaseMetaData nativeMetaData = nativeObject.getMetaData();
		return proxyFactory.newProxyObject(nativeMetaData);
	}

	public Statement createStatement() throws SQLException {
		Statement stmt = proxyFactory.newProxyObject(nativeObject.createStatement());

		return wireProxyConnectionOn(stmt);
	}

	private <T extends Statement> T wireProxyConnectionOn(T stmt) {
		ProxyStatementHandler statementHandler = getInvocationHandler(stmt, ProxyStatementHandler.class);
		statementHandler.setConnection((Connection) getTargetProxy());

		return stmt;
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		Statement stmt = proxyFactory.newProxyObject(nativeObject.createStatement(resultSetType, resultSetConcurrency));

		return wireProxyConnectionOn(stmt);
	}

	public CallableStatement prepareCall(String sql) throws SQLException {
		CallableStatement cstmt = proxyFactory.newProxyObject(nativeObject.prepareCall(sql));
		return wireProxyConnectionOn(cstmt);
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		CallableStatement cstmt = proxyFactory.newProxyObject(nativeObject.prepareCall(sql, resultSetType,
				resultSetConcurrency));
		return wireProxyConnectionOn(cstmt);
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {
		CallableStatement cstmt = proxyFactory.newProxyObject(nativeObject.prepareCall(sql, resultSetType,
				resultSetConcurrency, resultSetHoldability));
		return wireProxyConnectionOn(cstmt);
	}

	public PreparedStatement prepareStatement(String sql) throws SQLException {
		PreparedStatement stmt = proxyFactory.newProxyObject(nativeObject.prepareStatement(sql));
		return wireProxyConnectionOn(stmt);
	}

	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		PreparedStatement stmt = proxyFactory.newProxyObject(nativeObject.prepareStatement(sql, autoGeneratedKeys));
		return wireProxyConnectionOn(stmt);
	}

	public PreparedStatement prepareStatement(String sql, int columnIndexes[]) throws SQLException {
		PreparedStatement stmt = proxyFactory.newProxyObject(nativeObject.prepareStatement(sql, columnIndexes));
		return wireProxyConnectionOn(stmt);
	}

	public PreparedStatement prepareStatement(String sql, String columnNames[]) throws SQLException {
		PreparedStatement stmt = proxyFactory.newProxyObject(nativeObject.prepareStatement(sql, columnNames));
		return wireProxyConnectionOn(stmt);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
			throws SQLException {
		PreparedStatement stmt = proxyFactory.newProxyObject(nativeObject.prepareStatement(sql, resultSetType,
				resultSetConcurrency));
		return wireProxyConnectionOn(stmt);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {
		PreparedStatement stmt = proxyFactory.newProxyObject(nativeObject.prepareStatement(sql, resultSetType,
				resultSetConcurrency, resultSetHoldability));
		return wireProxyConnectionOn(stmt);
	}

}
